(window.dullscriptWebpackJsonp=window.dullscriptWebpackJsonp||[]).push([[27],{1312:function(z,F,b){function a(h,u,w){this.RUc=0;this.JVb=null;this.Sgb=this.dZb=this.mjb=0;this.OTc=h;this.iYa=u;this.r$=w;this.OTc=262144>h?h:262144;this.qwg=this.OTc-4*(this.iYa+25);this.reset()}function c(h,u,w,r,B,y,v,A,t){A=void 0===A?null:A;t=void 0===t?null:t;this.T=this.G=0;this.C=this.M=null;this.D=0;this.G=y;this.T=r;this.M=h;this.C=u;this.D=1E3*B+w;if(void 0===v?0:v)this.O=1;A&&(this.A=A);t&&(this.E=t)}function e(h,
u,w,r,B){this.T=h;this.L=u;this.S=w;this.I=r;this.V=B}function l(h,u,w,r,B,y){h&&(this.N=h);u&&(this.S=u);w&&(this.M=w);r&&(this.F=r);null!=B&&(this.L=B);null!=y&&(this.C=y)}b.r(F);z=b(0);var m=b(13);Object(z.a)(l,"SerializableExceptionEntry",null,[]);Object(z.a)(e,"SerializableLogCache",null,[]);c.prototype.y_g=function(){if(!this.E)return 0;var h=7,u=0;this.E.N&&(h+=6+c.haa(this.E.N),u++);this.E.S&&(h+=6+c.haa(this.E.S),u++);this.E.M&&(h+=6+c.haa(this.E.M),u++);this.E.F&&(h+=6+c.haa(this.E.F),u++);
this.E.L&&(h+=6+c.haa(this.E.L),u++);this.E.C&&(h+=6+c.haa(this.E.C),u++);1<u&&(h+=u-1);return h};c.prototype.X4g=function(){var h=b(1312).LogCache.vzi+c.haa(this.G)+c.haa(this.T)+this.M.length+c.haa(this.C)+c.haa(this.D)+this.y_g();1===this.O&&(h+=6);if(this.A){h+=7;for(var u=0,w=this.A.length;u<w;++u)h+=this.A[u].length+3}return h};c.haa=function(h){return(""+h).length};Object(z.a)(c,"SerializableLogEntry",null,[]);var n=b(396);b.d(F,"LogCache",function(){return a});a.prototype.reset=function(){this.JVb=
[];this.mjb=25;this.RUc=(new Date).getTime()};a.prototype.DFg=function(h){if(h){h.message=this.ePb(h.message,"message",h.tag);var u=h.jcd;u&&(u.name=this.ePb(u.name,"Exception.Name",h.tag),u.stack=this.ePb(u.stack,"Exception.Stack",h.tag),u.message=this.ePb(u.message,"Exception.Message",h.tag),u.file=this.ePb(u.file,"Exception.File",h.tag));if(h.jh)for(var w=0;w<h.jh.length;w++)h.jh[w].length>this.iYa&&(h.jh[w]=h.jh[w].substr(0,this.iYa-13)+"... [trimmed]",m.ULS.sendTraceTag(3465240,100,50,"Trimmed arg {0} for log {1}",
w,n.a(h.tag)));u=u?new l(u.name,u.stack,u.message,u.file,u.line,u.column):null;h=new c(h.message,h.category,h.level,h.timestamp-this.RUc,h.Jxd,h.tag,h.Xoi,h.jh,u);u=h.X4g();0<this.dZb&&u+this.mjb>this.dZb&&(w=this.count,this.reset(),m.ULS.sendTraceTag(0,100,15,"The log size is too large to be accepted by the server, throwing away {0} logs.",w));Array.add(this.JVb,h);this.mjb+=u}};a.prototype.ePb=function(h,u,w){var r=h;h&&h.length>this.iYa&&(r=h.substr(0,this.iYa-13)+"... [trimmed]",m.ULS.sendTraceTag(3465240,
100,50,"Trimmed {0} for log {1}",u,n.a(w)));return r};a.prototype.serialize=function(){return m.ULS.Kc(new e(this.RUc,this.JVb,this.r$,this.Sgb,1))};uk.Object.defineProperties(a.prototype,{count:{configurable:!0,enumerable:!0,get:function(){return this.JVb.length}},xEc:{configurable:!0,enumerable:!0,get:function(){return this.dZb},set:function(h){this.dZb=h}},Sli:{configurable:!0,enumerable:!0,get:function(){return this.mjb>this.qwg}},RVd:{configurable:!0,enumerable:!0,get:function(){return this.OTc}},
pxd:{configurable:!0,enumerable:!0,get:function(){return this.iYa}}});a.vzi=31;Object(z.a)(a,"LogCache",null,[53,54])},1462:function(z,F,b){function a(nb){this.Cfe=null;this.sui=nb}function c(nb){var pa=Ma.call(this)||this;pa.Bea=nb;pa.Xb();return pa}function e(nb){var pa=oa.call(this)||this;pa.Q4b=nb;Sys.Application.registerDisposableObject(pa);return pa}function l(){}function m(nb){nb=n.call(this,nb,!1,ea.AFrameworkApplication.Ld,Fa.a.instance.Nh("Common.IRefreshableAppSettings")||ea.AFrameworkApplication.ha,
Fa.a.instance.Nh("Common.IRefreshableAppSettings"))||this;nb.KTj="usu";nb.HTj="ufu";nb.wb=null;nb.Oa=new xa.a;return nb}function n(nb,pa,Ja,Da,ib){nb=w.call(this,ea.AFrameworkApplication.userSessionId,n.tLh(nb,pa,Ja),new r(void 0,ea.AFrameworkApplication.a6h(),Da.Cd("BulsUploadFrequencyInMs",6E4),void 0,void 0,void 0,void 0,ea.AFrameworkApplication.J2b))||this;nb.bH=null;nb.Knb=null;nb.rSc=null;nb.Yg=Ja;nb.zDa=Da;nb.Hnb=nb.zDa.Wa("RemoteUlsETag");nb.Hnb&&n.PNf(nb.zDa.Wa("RemoteUlsSuppressions"));
ib&&ib.VXc(Object(H.a)(nb,nb.mXi,"onSettingsRefreshed"));return nb}function h(nb){var pa=Ua.call(this)||this;pa.jh=nb;return pa}function u(nb,pa,Ja,Da){this.Sgb=nb;this.Bwe=pa;this.sessionId=Ja;this.version=Da}function w(nb,pa,Ja){Ja=void 0===Ja?null:Ja;this.WTb=0;this.yKc=!1;this.FEb=0;this.tjb=null;this.Xnb=0;this.Tg=null;this.CSd=this._disposing=!1;this.nC=this.OUc=this.uSb=this.pTb=0;this.yxc=!1;this.oWa=0;Ja||(Ja=new r);this.jTc=nb;this.U8=pa;this.U8.toLowerCase().startsWith("http:")&&document.URL.toLowerCase().startsWith("https:")&&
C.ULS.disable();this.eCg=Ja.Dig;this.EBg=Ja.zcg;this.Arg=Ja.VKe;this.fCg=Ja.kwe;this.gpg=Ja.hwe;this.Gra=new qa.LogCache(Ja.RVd,Ja.pxd,nb);this.Gra.xEc=Ja.xEc;this.aOd();this.fXf();this.gXf()}function r(nb,pa,Ja,Da,ib,Rb,wc,Cb){nb=void 0===nb?null:nb;pa=void 0===pa?null:pa;Ja=void 0===Ja?null:Ja;Da=void 0===Da?null:Da;ib=void 0===ib?null:ib;Rb=void 0===Rb?null:Rb;wc=void 0===wc?null:wc;Cb=void 0===Cb?null:Cb;this.pxd=3072;this.RVd=65536;this.Dig=6E4;this.zcg=2E3;this.VKe=1E4;this.kwe=5E3;this.hwe=
!1;this.xEc=0;null!=nb&&(this.pxd=nb);null!=pa&&(this.RVd=pa);null!=Ja&&(this.Dig=Ja);null!=Da&&(this.zcg=Da);null!=ib&&(this.VKe=ib);null!=Rb&&(this.kwe=Rb);null!=wc&&(this.hwe=wc);null!=Cb&&0<Cb&&(this.xEc=Cb)}function B(){}function y(){}function v(nb,pa,Ja,Da,ib){this.oGa=nb;this.lWa=pa;this.m2=Ja;this.uHc=Da;this.Uug=ib}function A(){this.File=this.Message=null;this.Column=this.Line=0;this.ClientAppVersion=this.Stack=null;this.AppMode=this.AppType=0;this.DeobfuscateWithSourceMaps=!1;this.DataPlumber=
this.SessionStartInfoJson=null;this.IsShuttingDown=!1;this.ErrorName=this.Flight=null}function t(){this.tb=null}function E(){$addHandler(document,"securitypolicyviolation",Object(H.a)(this,this.FGf,"onSecurityPolicyViolationEventHandler"))}b.r(F);z=b(724);F=b(0);var C=b(13),H=b(82),U=b(79);E.prototype.FGf=function(nb){nb=nb.rawEvent;var pa=nb.blockedURI;pa=U.a.Xda(pa);var Ja={};Ja.effectiveDirective=nb.effectiveDirective;Ja.violatedDirective=nb.violatedDirective;Ja.originalPolicy=nb.originalPolicy;
Ja.blockedURI=pa;Ja.disposition=nb.disposition;C.ULS.sendTraceTag(588084128,306,15,"{0}",Ja)};E.prototype.dispose=function(){$removeHandler(document,"securitypolicyviolation",Object(H.a)(this,this.FGf,"onSecurityPolicyViolationEventHandler"))};Object(F.a)(E,"ContentSecurityPolicyListener",null,[3]);var Q=b(254);t.prototype.init=function(){this.tb.resolve("Common.App.ContentSecurityPolicy.ContentSecurityPolicyListener")};t.prototype.dispose=function(){var nb=this.tb.Nh("Common.App.ContentSecurityPolicy.ContentSecurityPolicyListener");
nb&&nb.dispose()};t.prototype.hi=function(nb){this.tb=nb;this.tb.register(E,"Common.App.ContentSecurityPolicy.ContentSecurityPolicyListener").Ic().Nc(function(){return new E})};t.main=function(){Q.a.instance.nj(new t)};uk.Object.defineProperties(t.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return"Common.App.ContentSecurityPolicy"}}});Object(F.a)(t,"ContentSecurityPolicyPackage",null,[4,5]);var O=b(40);A.prototype.$Qd=function(){return O.c(this)};Object(F.a)(A,"DiagnosticsRequest",
null,[]);var ea=b(4),Z=b(525),S=b(495),I=b(28);v.prototype.Q0f=function(nb,pa){try{this.lah().send(this.NMh(nb,pa))}catch(Ja){C.ULS.sendTraceTag(6161306,201,10,"Could not send error report [{0}]",Ja.toString())}};v.prototype.lah=function(){var nb=new XMLHttpRequest;nb.open("POST",this.oGa,!0);nb.setRequestHeader("Content-Type","text/json; charset=utf-8");ea.AFrameworkApplication.userSessionId&&nb.setRequestHeader(S.a.KEc,I.a.ela(ea.AFrameworkApplication.userSessionId));this.lWa&&nb.setRequestHeader(S.a.E$a,
this.lWa);if(ea.AFrameworkApplication.Ld){var pa=ea.AFrameworkApplication.Ld.yT;pa&&nb.setRequestHeader(S.a.iFc,pa)}return nb};v.prototype.NMh=function(nb,pa){if(!nb)return null;pa=pa?"<stack>"+pa+"</stack>":"";var Ja=new A;Ja.Message=nb.message;Ja.File=nb.source;Ja.Line=nb.line;Ja.Column=nb.column;Ja.Stack=pa;Ja.ClientAppVersion=this.lWa;Ja.AppType=this.m2;Ja.AppMode=this.uHc;Ja.DeobfuscateWithSourceMaps=this.Uug;ea.AFrameworkApplication.ha.ra("JavaScriptCrashJsonTagEnabled")&&(Ja.SessionStartInfoJson=
ea.AFrameworkApplication.ha.appSettings.SessionStartInfoJson||"",ea.AFrameworkApplication.hg&&(Ja.DataPlumber=O.c(ea.AFrameworkApplication.hg)),Ja.IsShuttingDown=ea.AFrameworkApplication.Pg,Ja.Flight=ea.AFrameworkApplication.CF,Ja.ErrorName=Z.a.r1e(nb));return Ja.$Qd()};Object(F.a)(v,"JavascriptErrorReporter",null,[819]);y.prototype.build=function(nb,pa,Ja,Da,ib){return new v(nb,pa,Ja,Da,ib)};Object(F.a)(y,"JavascriptErrorReporterFactory",null,[795]);B.prototype.hi=function(nb){nb.register(y,"Common.App.Diagnostics.JavascriptErrorReporterFactory").as("Common.IJavascriptErrorReporterFactory").Ic().Nc(function(){return new y})};
B.prototype.init=function(){};B.prototype.dispose=function(){};B.main=function(){Q.a.instance.nj(new B)};uk.Object.defineProperties(B.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return"Common.App.Diagnostics"}}});Object(F.a)(B,"DiagnosticsPackage",null,[4,5]);var P=b(52),J=b(100),aa=b(224),ia=b(35),ba=b(161),ra=b(437),ka=b(36),da=b(58),ha=b(38),qa=b(1312);Object(F.a)(r,"UlsUploadConfiguration",null,[]);var Aa=b(396);w.prototype.fXf=function(){this.tjb=[];this.yKc=!1};w.prototype.nW=
function(nb){1<this.vgb?256>this.tjb.length?Array.add(this.tjb,nb):this.yKc=!0:(this.Gra.DFg(nb),this.Uzi(nb)&&!this.ZLe()?(this.wYe("LogIndicatesError in HandleTrace"),C.ULS.sendTraceTag(3731793,100,200,"Flushing error-level log (tag {0}) synchronously",Aa.a(nb.tag))):this.Gra.Sli&&(this.Qvb(!1,!0),C.ULS.sendTraceTag(3731794,100,200,"Flushing asynchronously due to cache size")))};w.prototype.Uzi=function(nb){return!!nb&&(1===nb.Jxd||10===nb.level)};w.prototype.ZLe=function(){return!1};w.prototype.dispose=
function(){this._disposing||(this._disposing=!0,this.IIh(),C.ULS.FSd(null),window.clearTimeout(this.oWa),window.clearTimeout(this.pTb),window.clearTimeout(this.uSb),this.uSb=this.pTb=this.oWa=0)};w.prototype.IIh=function(){this.mode=2;this.G9e();this.yxc=!1;this.gPe();this.wYe("FlushForAppClose")};w.prototype.WPb=function(nb,pa){nb.Sgb=this.FEb;return this.Eig(nb.serialize(),pa)?(this.FEb++,!0):!1};w.prototype.Eig=function(nb,pa){pa=this.gpg||!pa;this.Tg&&pa||(this.Tg=new XMLHttpRequest);if(0===this.Tg.readyState||
4===this.Tg.readyState)return this.Tg.open("POST",this.U8,pa),this.Tg.setRequestHeader("Content-Type","application/json"),this.Tg.setRequestHeader(w.lRd,this.jTc),pa&&(this.Tg.timeout=this.fCg),this.Tg.send(nb),!0;nb={};C.ULS.sendTraceTag(3731796,100,50,"Could not initiate upload {0}",(nb.UploadId=this.FEb,nb.XhrReadyState=this.Tg.readyState,nb));return!1};w.prototype.qZi=function(){this.Tg&&this.Tg.abort()};w.prototype.Oyc=function(nb,pa,Ja){try{return window.setTimeout(function(){C.ULS.sendTraceTag(3731797,
100,200,"Timeout ({0} ms) set by {1} is now firing.",pa,Ja);nb()},pa)}catch(Da){C.ULS.sendTraceTag(0,100,15,"SetTimeoutToLogOriginAndExecute: Calling Window.SetTimeout() failed with exception: {0}",Da.toString());if(!this.CSd){this.CSd=!0;try{nb()}finally{this.CSd=!1}}return 0}};w.prototype.gXf=function(){try{window.clearTimeout(this.pTb)}catch(nb){C.ULS.sendTraceTag(0,100,15,"ResetDelayedLoggingTimer: Calling Window.ClearTimeout() failed with exception: {0}",nb.toString())}this.pTb=this.Oyc(Object(H.a)(this,
this.G9e,"handleDelayedLogs"),this.Arg,"ResetDelayedLoggingTimer")};w.prototype.G9e=function(){var nb=this.tjb.length;if(nb){var pa=this.tjb,Ja=this.yKc;this.fXf();var Da={};C.ULS.sendTraceTag(3731798,100,50,"HandleDelayedLogs {0}",(Da.Count=nb,Da.Limit=256,Da.ExceededLimit=Ja,Da));this.Xnb++;for(Ja=0;Ja<nb;Ja++)this.nW(pa[Ja]);this.Xnb--}this.gXf()};w.prototype.aOd=function(){try{window.clearTimeout(this.uSb)}catch(nb){C.ULS.sendTraceTag(0,100,15,"ResetCadenceTimer: Calling Window.ClearTimeout() failed with exception: {0}",
nb.toString())}this.uSb=this.Oyc(Object(H.a)(this,this.Qvb,"flushImpl"),this.eCg,"ResetCadenceTimer")};w.prototype.gPe=function(){this.mode=0;this.yxc&&(this.yxc=!1,this.Qvb())};w.prototype.QMb=function(nb){return 2===this.mode||1===this.mode&&!nb};w.prototype.wYe=function(nb){C.ULS.sendTraceTag(3731800,100,200,"Flushing Synchronous due to {0}",nb);this.Qvb(!0)};w.prototype.Ovb=function(){this.uYe(0)};w.prototype.uYe=function(nb){this.oWa||(this.oWa=this.Oyc(Object(H.a)(this,this.Qvb,"flushImpl"),
nb,"FlushAsynchronous"))};w.prototype.Qvb=function(nb,pa){this.Xnb++;try{window.clearTimeout(this.oWa)}catch(Da){C.ULS.sendTraceTag(0,100,15,"FlushImpl: Calling Window.ClearTimeout() failed with exception: {0}",Da.toString())}this.oWa=0;if(this.Gra.count)if(!pa&&this.QMb(nb))C.ULS.sendTraceTag(3731801,100,200,"Not flushing ({0}) due to throttling",nb?"sync":"async"),this.yxc=!0;else{this.mode=nb?2:1;this.aOd();C.ULS.sendTraceTag(3731803,100,200,"Flushing ({0}) cached bULS logs ({1} logs)",nb?"sync":
"async",this.Gra.count);try{var Ja=this.WPb(this.Gra,nb)}catch(Da){this.qZi(),Ja=!1}Ja?(this.Gra.reset(),this.WTb=0):(this.WTb++,this.WTb<w.Htf?this.uYe(w.QOd):(this.Gra.reset(),this.FEb++,this.WTb=0))}else this.aOd();this.Xnb--};w.prototype.syb=function(){};w.prototype.npb=function(){};uk.Object.defineProperties(w.prototype,{vgb:{configurable:!0,enumerable:!0,get:function(){return C.ULS.vgb+this.Xnb}},mode:{configurable:!0,enumerable:!0,get:function(){return this.nC},set:function(nb){var pa=this.nC;
this.nC=nb;if(0===this.nC&&0!==pa)try{var Ja=this.OUc;this.OUc=0;window.clearTimeout(Ja)}catch(Da){C.ULS.sendTraceTag(0,100,15,"set_Mode: Calling Window.ClearTimeout() failed with exception: {0}",Da.toString())}else 0!==this.nC&&0===pa&&(this.OUc=this.Oyc(Object(H.a)(this,this.gPe,"endThrottling"),this.EBg,"ThrottlingMode Setter"))}}});w.Htf=3;w.QOd=15E3;w.lRd="X-UserSessionId";Object(F.a)(w,"UploadingUlsHost",null,[26,3]);Object(F.a)(u,"UploadState",null,[]);var Fa=b(84),ab=b(595),Ua=Sys.EventArgs;
Am(h,Ua);Object(F.a)(h,"UlsLoggingEventArgs",Sys.EventArgs,[]);var bb=b(128);Am(n,w);n.prototype.npb=function(nb){this.events.addHandler(n.ifg,nb)};n.prototype.mXi=function(nb,pa){pa.x8a(n.dYd)&&(this.Knb=this.v7e())};n.prototype.$Ph=function(){return Error().stack};n.prototype.v7e=function(){var nb=null;if(this.zDa.wz(n.dYd)){nb=new bb.a;for(var pa=this.zDa.Jw(n.dYd),Ja=0;Ja<pa.length;Ja++)nb.ia(pa[Ja],!0)}return nb};n.prototype.nW=function(nb){this.Knb||(this.Knb=this.v7e());if(this.Knb&&this.Knb.xb(nb.tag))try{!nb.jcd&&
this.w_c?nb.jcd=new ab.a(Error()):nb.message+=". JsCallStack: "+this.$Ph()}catch(Ja){nb.message+=" [Failed to add callstack for this tag. BUlsExceptionLoggingIsEnabled="+this.w_c+" ("+Ja.message+")]"}w.prototype.nW.call(this,nb);var pa=this.events.getHandler(n.ifg);nb=new h(nb);pa&&pa(null,nb)};n.prototype.WPb=function(nb,pa){if(this.Yg){if(!this.bEj)return!1;var Ja=nb.serialize();if(0<ea.AFrameworkApplication.J2b&&Ja.length>ea.AFrameworkApplication.J2b)return!1;nb.Sgb=this.FEb++;if(this.iDj())return this.Dxc(this.U8,
Ja),!0;this.Aqe(this.U8,Ja,pa&&!this.VGb?0:3,1,pa&&ea.AFrameworkApplication.Pg,nb.Sgb,this.VGb,this.KJf);return!0}return w.prototype.WPb.call(this,nb,pa)};n.prototype.gFd=function(nb){try{if(nb&&nb.data&&nb.data.responseHeaders&&n.Gfc in nb.data.responseHeaders){var pa=nb.data.responseHeaders[n.Gfc];pa!==this.Hnb&&(this.Hnb=pa,n.PNf(nb.data.responseHeaders[n.$af]))}}catch(Ja){C.ULS.sendTraceTag(593847297,100,50,"Failed to process tag suppressions. [Message: {0}] [Stack: {1}]",Ja.message,Ja.stack)}};
n.prototype.oDd=function(nb){var pa=this,Ja=nb.data;if(!Ja)C.ULS.sendTraceTag(5002497,100,15,"Request Item is null! RequestFailedEventArgs = {0}",nb);else if(13===Ja.status)C.ULS.sendTraceTag(6399108,100,50,"Request timed out in the ClientRequestManager queue. Falling back to default XHR."),this.Eig(Ja.request.get_body(),!1);else if(!Ja.responseHeaders)C.ULS.sendTraceTag(5002498,100,15,"Item.ResponseHeader is null! RequestItem id = {0}, responseXml = {1}, data = {2}, HttpStatusCode = {3}",Ja.id,Ja.dSa,
Ja.oe,Ja.httpStatus);else if(!(n.Oii in Ja.responseHeaders||(nb=Ja.httpStatus,400<=nb&&499>=nb))){var Da=Ja.state;Da.Bwe>=w.Htf||window.setTimeout(function(){pa.Aqe(Ja.request.get_url(),Ja.request.get_body(),3,Da.Bwe+1,!1,Da.Sgb,Da.sessionId,Da.version)},w.QOd)}};n.prototype.Aqe=function(nb,pa,Ja,Da,ib,Rb,wc,Cb){this.Yg.jm(nb,2,pa,this.bah(),!1,Ja,Object(H.a)(this,this.gFd,"onSuccessfulUpload"),Object(H.a)(this,this.oDd,"onFailedUpload"),new u(Rb,Da,wc,Cb),null,ib,this.zDa.Cd("BulsClientRequestManagerQueueTimeInMS",
3E4),void 0,"19",wc,void 0,Cb,void 0,[n.Gfc,n.$af])};n.prototype.bah=function(){var nb=null;this.Hnb&&(nb={},nb[n.Gfc]=this.Hnb);if(this.w_c){var pa=ea.AFrameworkApplication.sa,Ja=null;pa&&(Ja=pa.Qa);Ja&&(nb||(nb={}),nb[n.qai]=Ja.dda,nb[n.rai]=Ja.Yj,nb[n.wai]=ea.AFrameworkApplication.lli?"1":"0")}return nb};n.prototype.Dxc=function(nb,pa){this.Yg.Dxc(nb,pa)};n.prototype.iDj=function(){return ea.AFrameworkApplication.Pg||ea.AFrameworkApplication.Wtd};n.tLh=function(nb,pa,Ja){nb=n.tEg(nb,pa);return nb=
n.wHg(nb,Ja)};n.wHg=function(nb,pa){if(!pa)return nb;pa=pa.yT;return pa?nb=U.a.vl(nb,S.a.jFc,pa):nb};n.tEg=function(nb,pa){return pa?U.a.vl(nb,"build",ea.AFrameworkApplication.buildVersion):nb};n.PNf=function(nb){C.ULS.k4b();if(nb){nb=nb.split(",");nb=Cl(nb);for(var pa=nb.next();!pa.done;pa=nb.next())pa=parseInt(pa.value),!isNaN(pa)&&isFinite(pa)&&C.ULS.I_b(pa)}};uk.Object.defineProperties(n.prototype,{events:{configurable:!0,enumerable:!0,get:function(){return this.bH||(this.bH=new Sys.EventHandlerList)}},
VGb:{configurable:!0,enumerable:!0,get:function(){return null}},KJf:{configurable:!0,enumerable:!0,get:function(){return null}},w_c:{configurable:!0,enumerable:!0,get:function(){return this.zDa.ra("BUlsExceptionLoggingIsEnabled")}},gnj:{configurable:!0,enumerable:!0,get:function(){this.rSc||(this.rSc=this.zDa.Cd("bULSUploadRetryDelayWhenDisconnectedInMilliseconds",6E4));return this.rSc}},bEj:{configurable:!0,enumerable:!0,get:function(){var nb=this.Yg.b8a;return nb&&(new Date).getTime()-this.Yg.Lvi.getTime()>=
this.gnj?!0:!nb}}});n.Gfc="X-bULS-SuppressionETag";n.$af="X-bULS-SuppressedTags";n.qai="X-bULS-OfficeAppMode";n.rai="X-bULS-OfficeAppType";n.wai="X-bULS-UseSourceMaps";n.ifg="CommonUlsTraceEventKey";n.dYd="TagCallStackInclusionList";n.Oii="X-InvalidUlsJson";Object(F.a)(n,"CommonUlsHost",w,[]);var xa=b(96),Gb=b(1);Am(m,n);m.prototype.nW=function(nb){1===nb.Jxd&&Gb.EwaSettings.isChangeGateEnabled("OfficeVSO:5335621_IdentifyClientAsserts")&&(nb.message="Assert: "+nb.message);n.prototype.nW.call(this,
nb)};m.prototype.ZLe=function(){return!0};m.prototype.WPb=function(nb,pa){if(ea.AFrameworkApplication.Pg&&ea.AFrameworkApplication.Vcb)return!1;var Ja=null;this.$&&(Ja=this.$.Sb.Hc("UserAction","CommonUlsHostOverrides:UploadLogs"));pa=!ea.AFrameworkApplication.Vcb&&pa;nb=n.prototype.WPb.call(this,nb,pa);Ja&&Ja.stop();return nb};m.prototype.gFd=function(nb){n.prototype.gFd.call(this,nb);this.Oa.raiseEvent(this.KTj,nb)};m.prototype.oDd=function(nb){n.prototype.oDd.call(this,nb);this.Oa.raiseEvent(this.HTj,
nb)};uk.Object.defineProperties(m.prototype,{$:{configurable:!0,enumerable:!0,get:function(){this.wb||(this.wb=0<da.a.getRegisteredEwaInstances().length?da.a.Ds(document.body):null);return this.wb}}});Object(F.a)(m,"CommonUlsHostOverrides",n,[796,26,3]);l.prototype.w9g=function(nb){return new m(nb)};Object(F.a)(l,"CommonHostFactory",null,[818]);var $b=b(56),oa=ka.a;Am(e,oa);e.prototype.npb=function(nb){this.Q4b.npb(nb)};e.prototype.nW=function(nb){this.Q4b.nW(nb)};e.prototype.syb=function(nb){this.Q4b.syb(nb)};
e.prototype.Ovb=function(){this.Q4b.Ovb()};e.ka=function(nb,pa){pa=void 0===pa?null:pa;var Ja=new ba.a;Object(ra.a)(e,ea.AFrameworkApplication.xUa)||(pa=pa||new l,ha.a.Nfi(function(){if(ea.AFrameworkApplication.browserUlsIsEnabled){var Da=nb+"/RemoteUls.ashx";e.$&&(Da=e.HGg(Da));Da=pa.w9g(Da);ea.AFrameworkApplication.xUa=Da;C.ULS.gTa(50);C.ULS.FSd(Da);Ja.setResult(new e(Da))}else C.ULS.disable()},!ea.AFrameworkApplication.bCj()));return Ja.task};e.HGg=function(nb){var pa=e.$&&$b.d(e.$)?e.$.workbookContext.BuildVersion:
e.$.ya.BuildVersion;return U.a.vl(nb,"officeserverversion",pa)};uk.Object.defineProperties(e,{$:{configurable:!0,enumerable:!0,get:function(){e.wb||(e.wb=0<da.a.getRegisteredEwaInstances().length?da.a.Ds(document.body):null);return e.wb}}});e.wb=null;Object(F.a)(e,"EwaUlsHost",ka.a,[796,26,3]);var Ma=aa.a;Am(c,Ma);c.prototype.create=function(){var nb=this;ia.TaskExtensions.Ba(e.ka(this.Bea),function(pa){pa=pa.result;J.a.ij.Ha(135,pa);nb.Eb(pa)},this.la)};Object(F.a)(c,"EwaUlsHostFactory",aa.a,[]);
var Za=b(159),gb=b(34);a.prototype.S6i=function(nb,pa,Ja){!nb&&pa.source&&(nb=gb.a.fo(this.iBd,pa.source)+1,this.iBd[pa.source]=nb,nb-1&nb||C.ULS.sendTraceTag(537155536,0,15,"{0} errors seen for location={1}",nb,pa.source));pa.source&&1!==gb.a.fo(this.iBd,pa.source,1)||(C.ULS.sendTraceTag(537155535,0,50,"JavaSctipCrashProcessor.ProcessJavascriptError: Sending request to log JavaScript crash in the server"),this.sui.Q0f(pa,Ja))};uk.Object.defineProperties(a.prototype,{iBd:{configurable:!0,enumerable:!0,
get:function(){return this.Cfe||(this.Cfe={})}}});Object(F.a)(a,"JavaScriptCrashProcessor",null,[478]);var zb=b(60);Type.registerNamespace("_Ewa");Object(z.a)();Type.registerNamespace("Common.App.ContentSecurityPolicy");t.main();Type.registerNamespace("Common.App.Diagnostics");B.main();Type.registerNamespace("DiagUse");J.a.ij.Ha(43,new c(P.a.current.JL.ServerUriBase));(function(){try{Za.a.E8e().CWCT(function(nb){try{if(J.a.ij.Aa(42))C.ULS.sendTraceTag(537155532,0,50,"JavaScriptCrashProcessorBootstrapper: already initialized");
else{var pa=nb.result,Ja=Fa.a.instance.resolve("Common.IJavascriptErrorReporterFactory").build(P.a.current.JL.ServerUriBase+pa.LayoutsRelativeUri+"/diagnostics.ashx",pa.BuildVersion,1,0,!0);J.a.ij.Ha(42,new a(Ja));C.ULS.sendTraceTag(537155533,0,50,"JavaScriptCrashProcessorBootstrapper: initialized and ready to be used")}}catch(Da){C.ULS.sendTraceTag(537155531,0,15,"JavaScriptCrashProcessorBootstrapper: An exception occured while initializing JavascriptErrorProcessor, Message: {0}, Callstack: {1}",
Da.message,Da.stack)}},null,3,zb.a.current)}catch(nb){C.ULS.sendTraceTag(537155530,0,15,"JavaScriptCrashProcessorBootstrapper: an exception occured, Message: {0}, Callstack: {1}",nb.message,nb.stack)}})()}}]);

//# sourceMappingURL=https://artifacts.dev.azure.com/office/_apis/symbol/symsrv/EwaDS.tmcore.js.map/07dd39d89a8c8175e5624e9cdc5a2651/EwaDS.tmcore.js.map