(window.dullscriptWebpackJsonp=window.dullscriptWebpackJsonp||[]).push([[39],{1468:function(z,F,b){function a(S){var I=Z.call(this)||this;I.Qc=S;I.Xb();return I}function c(S,I){var P=this;this.Aje=this.dNc=!1;this.Wza=function(J,aa){(null===aa||void 0===aa?0:aa.HH)&&O.a.lPg([aa.HH])&&(P.Qwc=!0)};this.Yq=function(){P.Qwc=!1};this.fd=function(J,aa){Q.b(aa)&&P.pfa(!0);P.Qwc=!1};this.vd=function(){P.aS=P.$.aS;P.pfa()};this.mGf=function(){P.uT()};this.oFf=function(){P.aS=P.$.aS};this.GCd=function(){ea.g(P.$).Da.ar(P.GCd);
P.aS=P.$.aS};this.QZf=I;this.$=S;this.$.userOperationManager.Xu(this.oFf);this.$.fl(this.vd);this.$.ea.RKg(this.mGf);this.$.ea.ek(this.fd);this.$.g0b(this.Wza);this.$.ea.xQ(this.Yq);this.pfa()}function e(){this.SSc=this.VRc=this.cnb=this.tb=null}function l(S,I,P,J){this.bha=this.Vga=this.fha=this.eha=null;this.fFa=0;this.AE=this.RSc=this.yDa=this.vHc=this.bGa=null;this.Wd=S;this.J9=I;this.z2=P;this.rj=J;this.Hbe=!0;this.MM=!1;this.wA=3;this.qsa=!0}function m(S,I){this.Fs=null;this.eha=CommonUIStrings.l_SavedStatus;
this.fha=CommonUIStrings.l_SavingStatus;this.Vga=CommonUIStrings.l_ReadOnlyStatus;this.bha=CommonUIStrings.l_ReviewModeStatus;this.BUb=I;this.z2=S;this.wA=3;this.qsa=!0}function n(S){this.bha=this.Vga=this.fha=this.eha=null;this.jde=this.yx=this.MM=!1;this.eSc=this.yde=null;this.qde=0;this.vb=this.wde=null;this.z2=S;this.wA=3;this.Jkb=!0}b.r(F);z=b(0);var h=b(82),u=b(13),w=b(174),r=b(37);n.prototype.initialize=function(S,I,P){var J=this;this.eha=this.Mjd(S,I);this.fha=CommonUIStrings.l_SavingStatus;
this.Vga=CommonUIStrings.l_ReadOnlyStatus;this.bha=CommonUIStrings.l_ReviewModeStatus;this.z2&&this.z2.execute(function(aa){aa.RXc(Object(h.a)(J,J.TPb,"updateToSavingStatus"))});this.yx=!0;this.vb=P;return!0};n.prototype.pfa=function(S,I){this.MM=S;this.wA=I;this.uT(this.Jkb)};n.prototype.uT=function(S){!this.Jkb&&S&&(this.wde=new Date);this.Jkb=S;S=null;3===this.wA&&(S=this.Jkb?this.eha:this.fha);this.hkh(S)};n.prototype.Mjd=function(S,I){return S?String.format(CommonUIStrings.l_SavedToStatus,CommonUIStrings.l_OneDriveName):
I&&I.length?String.format(CommonUIStrings.l_SavedToStatus,I):CommonUIStrings.l_SavedStatus};n.prototype.TPb=function(){this.uT(!1)};n.prototype.nYh=function(){switch(this.wA){case 1:return this.Vga;case 2:return this.bha;default:return null}};n.prototype.bmi=function(S){return this.jde===this.MM&&this.qde===this.wA&&this.yde===S};n.prototype.pMe=function(S){var I=this;appChrome.getHeaderApi().then(function(P){P.updateDocumentTitleStatus(I.MM,S,I.nYh(),I.wde,I.Jkb);return null});this.eSc=null};n.prototype.hkh=
function(S){var I=this;this.yx&&w.c()&&!this.bmi(S)&&(r.a.OWf()?(this.eSc&&u.ULS.sendTraceTag(595146389,340,50,"Previous UpdateDocumentTitleStatus idle callback can be cancelled."),this.eSc=window.requestIdleCallback(function(){I.pMe(S)})):window.requestAnimationFrame(function(){I.pMe(S)}),this.jde=this.MM,this.yde=S,this.qde=this.wA)};Object(z.a)(n,"ReactSaveStatusUIHandler",null,[537]);var B=b(166);m.prototype.Gv=function(){var S=this;this.z2&&this.z2.execute(function(I){I.RXc(Object(h.a)(S,S.TPb,
"updateToSavingStatus"))});this.BUb.execute(function(I){S.Fs=I})};m.prototype.pfa=function(S,I){this.wA=I;3===I?this.uT(this.qsa):2===I?this.y_d(this.bha):this.y_d(this.Vga)};m.prototype.TPb=function(){this.uT(!1)};m.prototype.uT=function(S){this.qsa=S;this.y_d(this.qsa?this.eha:this.fha)};m.prototype.y_d=function(S){this.Fs&&this.Fs.Nj(B.a.CTj,this.U5g(S))};m.prototype.U5g=function(S){var I={};I.StatusText=S;return I};Object(z.a)(m,"SaveStatusPostMessageHandler",null,[537]);var y=b(93),v=b(121),
A=b(55);l.prototype.initialize=function(S,I){if(!this.Wd)return!1;this.eha=this.Mjd(S,I);this.fha=CommonUIStrings.l_SavingStatus;this.Vga=CommonUIStrings.l_ReadOnlyStatus;this.bha=CommonUIStrings.l_ReviewModeStatus;this.Gv();return!0};l.prototype.Mjd=function(S,I){return S?String.format(CommonUIStrings.l_SavedToStatus,CommonUIStrings.l_OneDriveName):I&&I.length?String.format(CommonUIStrings.l_SavedToStatus,I):CommonUIStrings.l_SavedStatus};l.prototype.Gv=function(){var S=this;this.J9&&this.J9.execute(function(I){I.qKg(Object(h.a)(S,
S.NIe,"createStatusAndModeElements"));I.hKg(Object(h.a)(S,S.HFj,"showHideSaveStatusElement"));I.KQj&&S.NIe(null,null)});this.z2&&this.z2.execute(function(I){I.RXc(Object(h.a)(S,S.TPb,"updateToSavingStatus"))})};l.prototype.Uv=function(){this.AE&&this.Wd&&this.Wd.TG(this.AE)};l.prototype.HFj=function(S,I){this.pfa("true"===I,this.wA)};l.prototype.pfa=function(S,I){this.MM=S;this.wA=I;this.vHc&&(this.vHc.style.display=this.MM||3===this.wA||!this.bGa?"none":"");this.yDa&&(this.yDa.style.display=this.MM||
3===this.wA?"none":"",this.yDa.innerText=1===this.wA?this.Vga:this.bha,this.yDa.title=1===this.wA?CommonUIStrings.l_ReadOnlyStatusTooltip:CommonUIStrings.l_ReviewModeStatusTooltip);this.RSc&&(this.RSc.style.display=this.MM||1===this.wA||!this.bGa&&!this.yDa?"none":"");this.AE&&(this.AE.style.display=this.MM||1===this.wA?"none":"",this.uT(this.qsa),this.AE.title=CommonUIStrings.l_SaveStatusTooltip)};l.prototype.NIe=function(S,I){S=document.getElementById(y.CuiHelper.Xaf);I&&I.L1j||!S||""===this.eha||
""===this.fha||""===this.Vga||""===this.bha||(this.bGa=document.getElementById(y.CuiHelper.y2b),this.vHc=y.CuiHelper.pua(S,"BreadcrumbAppModeDash","-",null,!1),this.yDa=y.CuiHelper.pua(S,"BreadcrumbAppModeStatus",1===this.wA?this.Vga:this.bha,null,!1),this.Zgg(this.yDa),this.RSc=y.CuiHelper.pua(S,"BreadcrumbSaveStatusDash","-",null,!1),this.AE=y.CuiHelper.pua(S,"BreadcrumbSaveStatus",this.eha,null,!1),this.Zgg(this.AE),this.pfa(this.MM,this.wA))};l.prototype.TPb=function(){this.uT(!1)};l.prototype.uT=
function(S){this.qsa=S;this.xYj(this.qsa?this.eha:this.fha)};l.prototype.xYj=function(S){!this.AE||3!==this.wA&&2!==this.wA||(this.Hbe&&!this.qsa?(this.fFa=this.AE.offsetWidth<this.fFa?this.fFa:this.AE.offsetWidth,this.AVj(this.fha),this.Hbe=!1):this.AE.innerText=S)};l.prototype.Zgg=function(S){S.style.direction=this.rj?"rtl":"ltr";S.style.width="auto";S.style.textAlign=this.rj?"right":"left";S.style.display=this.MM?"none":"";S.setAttribute("Unselectable","on")};l.prototype.AVj=function(S){this.AE&&
(this.AE.style.width="",this.AE.innerText=S,this.fFa=this.AE.offsetWidth<this.fFa?this.fFa:this.AE.offsetWidth,S=v.a.wB(this.AE),this.AE.style.width=this.fFa-A.a.FD(S.paddingLeft)-A.a.FD(S.paddingRight)+1+"px")};Object(z.a)(l,"SaveStatusUIHandler",null,[537]);var t=b(4),E=b(92);e.prototype.hi=function(S){var I=this;this.tb=S;t.AFrameworkApplication.ha.ra("PostMessageEmbedded")&&t.AFrameworkApplication.hideHeaderEmbedded?this.tb.register(m,"Common.App.SaveStatus.SaveStatusPostMessageHandler").as("Common.App.SaveStatus.ISaveStatusUIHandler").Ic().Nc(function(){return new m(I.tb.qc("Common.App.HostNotification.EditNotificationEventSource"),
I.tb.qc("Postmessage.IHostPostmessenger"))}):t.AFrameworkApplication.sa.Qa.ylf||(t.AFrameworkApplication.sa.Qa.isReactSharedHeaderUxEnabled?this.tb.register(n,"Common.App.SaveStatus.ReactSaveStatusUIHandler").as("Common.App.SaveStatus.ISaveStatusUIHandler").Ic().Nc(function(){return new n(I.tb.qc("Common.App.HostNotification.EditNotificationEventSource"))}):this.tb.register(l,"Common.App.SaveStatus.SaveStatusUIHandler").as("Common.App.SaveStatus.ISaveStatusUIHandler").Ic().Nc(function(){return new l(E.EventHandlerManager.instance,
I.tb.qc("Common.App.Header.HeaderEventSource"),I.tb.qc("Common.App.HostNotification.EditNotificationEventSource"),t.AFrameworkApplication.isRtl)}))};e.prototype.init=function(){t.AFrameworkApplication.ha.tv(Object(h.a)(this,this.OB,"onFullAppSettingsReady"))};e.prototype.OB=function(){var S=t.AFrameworkApplication.ha,I=!!t.AFrameworkApplication.sa.Qa&&4===t.AFrameworkApplication.sa.Qa.Yj;if(S.ra("WordEditorAutoSaveImprovementIsEnabled")||S.ra("PptEditorSaveStatusInHeaderEnabled")||I&&S.ra("SimplifiedReactRibbonUxIsEnabled")||
S.ra("ExcelSaveStatusInHeaderEnabled")||S.ra("VisioSaveStatusInHeaderEnabled"))t.AFrameworkApplication.ha.ra("PostMessageEmbedded")&&t.AFrameworkApplication.hideHeaderEmbedded?(this.SSc=this.tb.resolve("Common.App.SaveStatus.SaveStatusPostMessageHandler"))&&this.SSc.Gv():t.AFrameworkApplication.sa.Qa.ylf||(t.AFrameworkApplication.sa.Qa.isReactSharedHeaderUxEnabled?(this.VRc=this.tb.resolve("Common.App.SaveStatus.ReactSaveStatusUIHandler"))&&this.VRc.initialize(S.ra("IsSkyDrive"),S.Wa("HostNameToIncludeInSavedStatus"),
t.AFrameworkApplication.ha):(this.cnb=this.tb.resolve("Common.App.SaveStatus.SaveStatusUIHandler"))&&this.cnb.initialize(S.ra("IsSkyDrive"),S.Wa("HostNameToIncludeInSavedStatus")))};e.prototype.dispose=function(){this.cnb&&this.cnb.Uv()};uk.Object.defineProperties(e.prototype,{name:{configurable:!0,enumerable:!0,get:function(){return"Common.App.SaveStatus"}}});Object(z.a)(e,"PackageManager",null,[4,5]);F=b(254);var C=b(10),H=b(84),U=b(224),Q=b(227),O=b(29),ea=b(20);c.prototype.dispose=function(){this.$&&
(this.$.Bl(this.vd),this.$.fvc(this.Wza),this.$.userOperationManager&&this.$.userOperationManager.dr(this.oFf),this.$.ea&&(this.$.ea.iij(this.mGf),this.$.ea.tk(this.fd),this.$.ea.DX(this.Yq)),ea.g(this.$)&&ea.g(this.$).Da&&ea.g(this.$).Da.ar(this.GCd))};c.prototype.pfa=function(S){S=!this.$.isEditMode||(void 0===S?!1:S);this.QZf.pfa(S,this.$.isEditMode?3:1);this.uT()};c.prototype.uT=function(){this.$.isEditMode&&this.QZf.uT(!this.aS&&!this.Mvi&&!this.Qwc)};uk.Object.defineProperties(c.prototype,{Mvi:{configurable:!0,
enumerable:!0,get:function(){return this.$.ea?this.$.ea.Tnf:!1}},aS:{configurable:!0,enumerable:!0,get:function(){return this.dNc},set:function(S){S?this.dNc=!0:ea.g(this.$)&&ea.g(this.$).Da&&(ea.g(this.$).Da.iI()?this.dNc=!1:ea.g(this.$).Da.aq(this.GCd));this.uT()}},Qwc:{configurable:!0,enumerable:!0,get:function(){return this.Aje},set:function(S){this.Aje=S;this.uT()}}});Object(z.a)(c,"SaveStatusManager",null,[3]);var Z=U.a;Am(a,Z);a.prototype.create=function(){var S=this,I=H.a.instance;I.qc("Common.App.SaveStatus.ISaveStatusUIHandler").execute(function(P){var J=
new c(S.Qc,P);I.register(c,"Microsoft.Office.Excel.WebUI.Client.SaveStatus.SaveStatusManager").Ic().Nc(function(){return J});S.Eb(I.resolve("Microsoft.Office.Excel.WebUI.Client.SaveStatus.SaveStatusManager"))})};a.ka=function(S){S.da.Ha(299,new a(S))};Object(z.a)(a,"SaveStatusFactory",U.a,[]);Type.registerNamespace("_Ewa");Type.registerNamespace("Common.App.SaveStatus");F.a.instance.nj(new e);C.a.Ga(a.ka)}}]);

//# sourceMappingURL=https://artifacts.dev.azure.com/office/_apis/symbol/symsrv/EwaDS.savestatus.js.map/67c29b343196ec5b7661fffbd530840f/EwaDS.savestatus.js.map